# Generated by Django 3.1.1 on 2020-09-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200920_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='toys',
            field=models.ManyToManyField(to='main_app.Toy'),
        ),
    ]
